### ISSUE TITLE
Not working with Stock OS 1.1.1

### ISSUE THREAD

**Issue by adtither** [ahmadteeb/EmuDrop#14]
App doesn't seem to open. Just says loading and then exits out. 

Any help would be greatly appreciated!

**Comment by ahmadteeb** [comment]
Can you send me the logs or try stating the app using ssh?

**Comment by adtither** [comment]
Just tested v2.1.3 and still doesn't seem to be opening unfortunately. How do I go about getting the logs?

**Comment by ahmadteeb** [comment]
ssh root@your_TSP_IP

cd /mnt/SDCARD/Apps/EmuDrop

./launch.sh

then send me what you see

**Comment by adtither** [comment]
Getting the following when trying to connect:
ssh: connect to host 192.168.0.227 port 22: Connection refused

**Comment by ahmadteeb** [comment]
launch.sh not found 

check if launch.sh exists or not using 'ls' command
if exists run 'chmod +x launch.sh' then ./launch.sh

**Comment by adtither** [comment]
Just tested and getting the following. Worth noting when launching from ssh the screen is flickering on the device showing some UI:

launch.sh: line 11: /mnt/SDCARD/System/usr/trimui/scripts/infoscreen.sh: not found
launch.sh: line 18: /mnt/SDCARD/System/usr/trimui/scripts/infoscreen.sh: not found
launch.sh: line 20: ./app_ota.sh: not found
launch.sh: line 21: ./db_ota.sh: not found
UserWarning: pysdl2-dll is installed as source-only, meaning that it does not contain any binaries and will be ignored by PySDL2.
sh: setterm: not found
current_mode 1024x768
SDL_UDEV_DEVICEADDED 2 /dev/input/event1
SDL_UDEV_DEVICEADDED 8 /dev/audio
SDL_UDEV_DEVICEADDED 8 /dev/dsp
SDL_UDEV_DEVICEADDED 2 /dev/input/event2
SDL_UDEV_DEVICEADDED 8 /dev/mixer
SDL_UDEV_DEVICEADDED 8 /dev/snd/pcmC0D0c
SDL_UDEV_DEVICEADDED 8 /dev/snd/pcmC0D0p
SDL_UDEV_DEVICEADDED 8 /dev/snd/controlC0
SDL_UDEV_DEVICEADDED 2 /dev/input/event0
SDL_UDEV_DEVICEADDED 6 /dev/input/event3
SDL_UDEV_DEVICEADDED 6 /dev/input/js0
SDL_UDEV_DEVICEADDED 8 /dev/snd/seq
SDL_UDEV_DEVICEADDED 8 /dev/sequencer
SDL_UDEV_DEVICEADDED 8 /dev/sequencer2
SDL_UDEV_DEVICEADDED 8 /dev/snd/timer
SDL_UDEV_DEVICEADDED 2 /dev/input/event1
SDL_UDEV_DEVICEADDED 8 /dev/audio
SDL_UDEV_DEVICEADDED 8 /dev/dsp
SDL_UDEV_DEVICEADDED 2 /dev/input/event2
SDL_UDEV_DEVICEADDED 8 /dev/mixer
SDL_UDEV_DEVICEADDED 8 /dev/snd/pcmC0D0c
SDL_UDEV_DEVICEADDED 8 /dev/snd/pcmC0D0p
SDL_UDEV_DEVICEADDED 8 /dev/snd/controlC0
SDL_UDEV_DEVICEADDED 2 /dev/input/event0
SDL_UDEV_DEVICEADDED 6 /dev/input/event3
SDL_UDEV_DEVICEADDED 6 /dev/input/js0
SDL_UDEV_DEVICEADDED 8 /dev/snd/seq
SDL_UDEV_DEVICEADDED 8 /dev/sequencer
SDL_UDEV_DEVICEADDED 8 /dev/sequencer2
SDL_UDEV_DEVICEADDED 8 /dev/snd/timer
2026-01-03 13:45:22,542 - utils.logger - INFO - SDL subsystems initialized successfully
MALI_CreateWindow:0x3daea660 done.
2026-01-03 13:45:22,577 - utils.logger - INFO - Window created successfully with dimensions: 1024x768
2026-01-03 13:45:22,706 - utils.logger - INFO - Created renderer: software
2026-01-03 13:45:22,716 - utils.logger - INFO - Loaded font: /mnt/SDCARD/Apps/EmuDrop/assets/fonts/arial.ttf
2026-01-03 13:45:22,721 - utils.logger - INFO - Loading screen font loaded: /mnt/SDCARD/Apps/EmuDrop/assets/fonts/arial.ttf
2026-01-03 13:45:22,726 - utils.logger - INFO - Loading screen font loaded: /mnt/SDCARD/Apps/EmuDrop/assets/fonts/arial.ttf
2026-01-03 13:45:22,729 - utils.logger - INFO - Views initialized with current screen dimensions
2026-01-03 13:45:22,746 - data.database - INFO - Database connection initialized successfully
2026-01-03 13:45:22,750 - utils.logger - INFO - Number of joysticks detected: 1
2026-01-03 13:45:22,753 - utils.logger - INFO - Joystick initialized successfully
2026-01-03 13:45:23,343 - data.database - ERROR - Error fetching platforms: no such table: platforms
Traceback (most recent call last):
  File "data/database.py", line 51, in get_platforms
    self.cursor.execute(query)
sqlite3.OperationalError: no such table: platforms

**Comment by ahmadteeb** [comment]
Are you sure you have installed the latest version 2.1.4?

**Comment by adtither** [comment]
Still not opening. For some reason now when I sh launch.,sh it attempts to download a version and leaves the folder empty:

root@TinaLinux:/mnt/SDCARD/Apps/EmuDrop# sh launch.sh
launch.sh: line 11: /mnt/SDCARD/System/usr/trimui/scripts/infoscreen.sh: not found
launch.sh: line 18: /mnt/SDCARD/System/usr/trimui/scripts/infoscreen.sh: not found
app_ota.sh: line 79: /mnt/SDCARD/System/usr/trimui/scripts/infoscreen.sh: not found
sh: =~: unknown operand
Local version: v0.0.0
Latest version: v2.1.4
app_ota.sh: line 97: /mnt/SDCARD/System/usr/trimui/scripts/infoscreen.sh: not found
app_ota.sh: line 97: /mnt/SDCARD/System/usr/trimui/scripts/infoscreen.sh: not found
Downloading the latest release from: https://github.com/ahmadteeb/EmuDrop/releases/download/v2.1.4/EmuDrop.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 17.1M  100 17.1M    0     0   425k      0  0:00:41  0:00:41 --:--:-- 1025k
Cleaning local files (except ZIP)...
find: ./assets: No such file or directory
Extracting new version...
app_ota.sh: line 97: unzip: not found
Removing the ZIP file...
app_ota.sh: line 97: /mnt/SDCARD/System/usr/trimui/scripts/infoscreen.sh: not found
sh: can't open 'db_ota.sh'
launch.sh: line 31: ./EmuDrop: not found
root@TinaLinux:/mnt/SDCARD/Apps/EmuDrop#

**Comment by ahmadteeb** [comment]
i have uploaded new one for stock os EmuDropStockOS.tar.gz 

try it and tell me what happen

https://github.com/ahmadteeb/EmuDrop/releases/download/v2.1.4/EmuDropStockOS.tar.gz

**Comment by ahmadteeb** [comment]
just extract it on apps folder

**Comment by adtither** [comment]
Removed the following line:

$INFOSCREEN -m "Checking internet connection..." -t 0.2

I didn't use SSH to open this time, but still not opening.

**Comment by adtither** [comment]
Didn't work unfortunately. For confirmation this is what I have:

```
#!/bin/bash
APP_DIR=$(dirname "$0")
cd $APP_DIR

chmod -R 777 .

export PYSDL2_DLL_PATH="/usr/trimui/lib/"
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/mnt/SDCARD/System/lib/

if ping -c 1 8.8.8.8 > /dev/null 2>&1; then
    echo "Internet connection detected."
else 
    echo "No internet connection. Press B to exit."
    exit
fi

echo performance >/sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
echo 1608000 >/sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
echo 1 > /tmp/stay_awake #keep screen awake

export ROMS_DIR="/mnt/SDCARD/Roms/"
export IMGS_DIR="/mnt/SDCARD/Imgs/{SYSTEM}/{IMAGE_NAME}.png"
export EXECUTABLES_DIR="$APP_DIR/assets/executables/"

chmod 777 EmuDrop

./EmuDrop
rm /tmp/stay_awake
```

**Comment by ahmadteeb** [comment]
now should be solved

remove the app and reinstall it from this link
https://github.com/ahmadteeb/EmuDrop/releases/download/v2.1.6/EmuDropStockOS.tar.gz

**Comment by adtither** [comment]
Unfortunatly still not opening on the Brick and when I SSH I get:

```
Cleaning local db file if exits
Moving db file to assets
db_ota.sh: line 89: -m: not found
UserWarning: pysdl2-dll is installed as source-only, meaning that it does not contain any binaries and will be ignored by PySDL2.
Traceback (most recent call last):
  File "sdl2/dll.py", line 362, in <module>
  File "sdl2/dll.py", line 253, in __init__
RuntimeError: could not find any library for SDL2 (PYSDL2_DLL_PATH: /usr/lib/)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 8, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 450, in exec_module
  File "app.py", line 19, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 450, in exec_module
  File "sdl2/__init__.py", line 2, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 450, in exec_module
  File "sdl2/dll.py", line 364, in <module>
ImportError: could not find any library for SDL2 (PYSDL2_DLL_PATH: /usr/lib/)
[PYI-8679:ERROR] Failed to execute script 'main' due to unhandled exception!
root@TinaLinux:/mnt/SDCARD/Apps/EmuDropStockOS#
```

**Comment by ahmadteeb** [comment]
I have edit now the path of PYSDL2_DLL
https://github.com/ahmadteeb/EmuDrop/releases/download/v2.1.6/EmuDropStockOS.tar.gz

delete it and reinstall from the above link, tell me if it works

**Comment by adtither** [comment]
Still not opening when opening from the Brick but this is what I get from SSH:

Cleaning local db file if exits
Moving db file to assets
db_ota.sh: line 89: -m: not found
UserWarning: pysdl2-dll is installed as source-only, meaning that it does not contain any binaries and will be ignored by PySDL2.
sh: setterm: not found
current_mode 1024x768
SDL_UDEV_DEVICEADDED 2 /dev/input/event1
SDL_UDEV_DEVICEADDED 8 /dev/audio
SDL_UDEV_DEVICEADDED 8 /dev/dsp
SDL_UDEV_DEVICEADDED 2 /dev/input/event2
SDL_UDEV_DEVICEADDED 8 /dev/mixer
SDL_UDEV_DEVICEADDED 8 /dev/snd/pcmC0D0c
SDL_UDEV_DEVICEADDED 8 /dev/snd/pcmC0D0p
SDL_UDEV_DEVICEADDED 8 /dev/snd/controlC0
SDL_UDEV_DEVICEADDED 2 /dev/input/event0
SDL_UDEV_DEVICEADDED 6 /dev/input/event3
SDL_UDEV_DEVICEADDED 6 /dev/input/js0
SDL_UDEV_DEVICEADDED 8 /dev/snd/seq
SDL_UDEV_DEVICEADDED 8 /dev/sequencer
SDL_UDEV_DEVICEADDED 8 /dev/sequencer2
SDL_UDEV_DEVICEADDED 8 /dev/snd/timer
SDL_UDEV_DEVICEADDED 2 /dev/input/event1
SDL_UDEV_DEVICEADDED 8 /dev/audio
SDL_UDEV_DEVICEADDED 8 /dev/dsp
SDL_UDEV_DEVICEADDED 2 /dev/input/event2
SDL_UDEV_DEVICEADDED 8 /dev/mixer
SDL_UDEV_DEVICEADDED 8 /dev/snd/pcmC0D0c
SDL_UDEV_DEVICEADDED 8 /dev/snd/pcmC0D0p
SDL_UDEV_DEVICEADDED 8 /dev/snd/controlC0
SDL_UDEV_DEVICEADDED 2 /dev/input/event0
SDL_UDEV_DEVICEADDED 6 /dev/input/event3
SDL_UDEV_DEVICEADDED 6 /dev/input/js0
SDL_UDEV_DEVICEADDED 8 /dev/snd/seq
SDL_UDEV_DEVICEADDED 8 /dev/sequencer
SDL_UDEV_DEVICEADDED 8 /dev/sequencer2
SDL_UDEV_DEVICEADDED 8 /dev/snd/timer
2026-01-28 13:11:30,611 - utils.logger - INFO - SDL subsystems initialized successfully
MALI_CreateWindow:0x2194d190 done.
2026-01-28 13:11:30,650 - utils.logger - INFO - Window created successfully with dimensions: 1024x768
2026-01-28 13:11:30,778 - utils.logger - INFO - Created renderer: software
2026-01-28 13:11:30,783 - utils.logger - INFO - Loaded font: /mnt/SDCARD/Apps/EmuDropStockOS/assets/fonts/arial.ttf
2026-01-28 13:11:30,787 - utils.logger - INFO - Loading screen font loaded: /mnt/SDCARD/Apps/EmuDropStockOS/assets/fonts/arial.ttf
2026-01-28 13:11:30,792 - utils.logger - INFO - Loading screen font loaded: /mnt/SDCARD/Apps/EmuDropStockOS/assets/fonts/arial.ttf
2026-01-28 13:11:30,795 - utils.logger - INFO - Views initialized with current screen dimensions
2026-01-28 13:11:30,802 - data.database - INFO - Database connection initialized successfully
2026-01-28 13:11:30,805 - utils.logger - INFO - Number of joysticks detected: 1
2026-01-28 13:11:30,809 - utils.logger - INFO - Joystick initialized successfully
2026-01-28 13:11:33,771 - data.database - INFO - Retrieved 41 platforms

**Comment by ahmadteeb** [comment]
Its not the same delete everything and redownload it from the latest link

**Comment by adtither** [comment]
That is what I had done. Did it again, but still getting the same result

**Comment by ahmadteeb** [comment]
It's so weird it has been tested with others and works fine

Can show me what inside launch.sh?

Also show me what inside version.txt

**Comment by adtither** [comment]
Here is what is in the launch.sh. I'm not seeing the version.txt

#!/bin/bash
APP_DIR=$(dirname "$0")
cd $APP_DIR

chmod -R 777 .

export PYSDL2_DLL_PATH="/usr/trimui/lib/"
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/mnt/SDCARD/System/lib/

if ping -c 1 8.8.8.8 > /dev/null 2>&1; then
    echo "Internet connection detected."
else 
    echo "No internet connection. Press B to exit."
    exit
fi

sh app_ota.sh
sh db_ota.sh

echo performance >/sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
echo 1608000 >/sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
echo 1 > /tmp/stay_awake #keep screen awake

export ROMS_DIR="/mnt/SDCARD/Roms/"
export IMGS_DIR="/mnt/SDCARD/Imgs/{SYSTEM}/{IMAGE_NAME}.png"
export EXECUTABLES_DIR="$APP_DIR/assets/executables/"

"$APP_DIR/EmuDrop"
rm /tmp/stay_awake

**Comment by ahmadteeb** [comment]
sh app_ota.sh
sh db_ota.sh

Remove these lines from launch.sh

And try

**Comment by adtither** [comment]
Still no luck unfortunately

**Comment by cgeneral19** [comment]
Any update on this issue?

**Comment by JamBeatss** [comment]
**Root cause: `launch.sh` uses `#!/bin/bash`, but TrimUI stock OS has no `/bin/bash`.**

Stock OS is busybox-based. The Apps launcher execs `launch.sh` directly, so with a `#!/bin/bash` shebang the kernel can't find the interpreter and the process dies *before executing a single line* — no output, no log file, instant bounce back to the app menu. That's exactly the "just says loading and then exits out" symptom.

Every other app that launches correctly on this device ships `#!/bin/sh`:

| App | Shebang | Launches |
| --- | --- | --- |
| BootRetroArch | `#!/bin/sh` | ✅ |
| JukaHub | `#!/bin/sh` | ✅ |
| PixelReader | `#!/bin/sh` | ✅ |
| LedController | `#!/bin/sh` | ✅ |
| user_guide | `#!/bin/sh` | ✅ |
| **EmuDrop v2.1.6** | **`#!/bin/bash`** | ❌ |

**Fix:** change the first line of `platform/Trimui Smart Pro/EmuDropStockOS/launch.sh` from `#!/bin/bash` to `#!/bin/sh`. The rest of that script is already POSIX-clean, so no other changes are needed to make the app start.

Confirmed working afterwards on a **TrimUI Brick, stock OS 1.1.1, EmuDrop v2.1.6** — app launches, catalog loads, downloads work.

---

**Second, related issue (same firmware):** `launch.sh` invokes the updaters as `sh app_ota.sh` / `sh db_ota.sh`, but both scripts use bash-only syntax — `[[ ... ]]`, `=~`, and `==`. busybox `ash` can't parse those, so the app/database OTA updates misbehave on stock OS even once the app does start. POSIX equivalents (`[ ... ]`, `=`, and a `case` statement for the `^v` prefix check) work under both shells.

Also, `db_ota.sh` calls `$INFOSCREEN`, but the v2.1.6 stock-OS `launch.sh` never sets it — so each of those progress messages runs as an empty command. The older release did `export INFOSCREEN="/mnt/SDCARD/System/usr/trimui/scripts/infoscreen.sh"`; that line appears to have been dropped.

---

Full patch for all three scripts (`launch.sh`, `app_ota.sh`, `db_ota.sh`): https://gist.github.com/JamBeatss/31066abf899cfab9cd2b7541dca8fdc5

**Comment by ahmadteeb** [comment]
@JamBeatss 
hey can you do pull request?
